# Generated by Django 4.2.30 on 2026-04-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_orderitem_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('ONLINE', 'Online'), ('SHOP', 'Shop')], default='COD', max_length=20),
        ),
    ]
