# Generated by Django 4.2.28 on 2026-03-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_order_currency_order_discount_amount_order_market_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Cash on Delivery', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(default='Standard Delivery', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='PKR', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='market',
            field=models.CharField(default='Pakistan', max_length=100),
        ),
    ]
