# Generated by Django 4.2.28 on 2026-04-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_purchaseorder_expected_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='items_per_carton',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='packaging_type',
            field=models.CharField(choices=[('SINGLE', 'Single Units'), ('CARTON', 'Carton Pack')], default='SINGLE', max_length=10),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
