# Generated by Django 4.2.28 on 2026-03-12 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_customercategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerCategory',
        ),
    ]
