# Generated by Django 4.2.29 on 2026-04-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('confirmed', 'Confirmed'), ('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancel_requested', 'Cancellation Requested'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], db_index=True, default='ordered', max_length=20),
        ),
    ]
