# Generated by Django 4.2.29 on 2026-04-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_remove_purchaseorder_tracking_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('ONLINE_PAYMENT', 'Online Payment')], default='CASH', max_length=30),
        ),
    ]
