# Generated by Django 4.2.29 on 2026-04-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='packaging_type',
            field=models.CharField(choices=[('piece', 'Piece'), ('pack', 'Pack'), ('carton', 'Carton')], default='piece', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='pieces_per_unit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
