# Generated by Django 4.2.29 on 2026-04-06 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_supplier'),
        ('sales', '0011_purchaseorderitem_packaging_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='company.supplier', verbose_name='Assigned Supplier Profile'),
        ),
    ]
