# Generated by Django 4.2.29 on 2026-04-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_purchaseorder_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='tracking_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('received', 'Received'), ('partially_received', 'Partially Received'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=25),
        ),
    ]
