# Generated by Django 4.2.29 on 2026-04-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_purchaseorder_tracking_id_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ordered', 'Ordered'), ('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('received', 'Received'), ('partially_received', 'Partially Received'), ('cancelled', 'Cancelled')], db_index=True, default='ordered', max_length=25),
        ),
    ]
