# Generated by Django 4.2.29 on 2026-04-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_salereturn_alter_order_status_salereturnitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereturn',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
