# Generated by Django 4.2.29 on 2026-04-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_salereturn_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
