# Generated by Django 4.2.29 on 2026-04-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_purchaseorderitem_size_purchaseorderitem_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('ONLINE', 'Online Payment'), ('CHEQUE', 'Cheque'), ('CREDIT', 'Credit')], default='CASH', max_length=30),
        ),
    ]
