# Generated by Django 4.2.29 on 2026-05-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_order_whatsapp_number_order_whatsapp_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
