# Generated by Django 4.2.28 on 2026-06-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_purchaseorder_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid')], default='PAID', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='refund_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('online', 'Online'), ('wallet', 'Mobile Wallet'), ('credit_note', 'Credit Note'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='refund_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Settled')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='refund_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('online', 'Online'), ('wallet', 'Mobile Wallet'), ('credit_note', 'Store Credit'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='refund_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Refunded')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
