# Generated by Django 4.2.29 on 2026-07-06 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_remove_supplier_contact_supplier_avatar_and_more'),
        ('sales', '0029_order_discount_order_shipping_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='supplier.supplier'),
        ),
    ]
