# Generated by Django 4.2.29 on 2026-07-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rider_reported_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
