# Generated by Django 4.2.29 on 2026-07-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_order_rider_reported_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rider_reported_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
