# Generated by Django 4.2.29 on 2026-07-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_order_rider_reported_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_reported_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
