# Generated by Django 4.2.29 on 2026-07-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0034_order_customer_reported_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='proof_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery/proofs/'),
        ),
        migrations.AddField(
            model_name='order',
            name='proof_lat',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='proof_lng',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
