# Generated by Django 4.2.30 on 2026-10-06 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_product_batch'),
        ('sales', '0037_order_sale_date_order_salesperson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productbatch'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
