# Generated by Django 4.2.30 on 2026-10-07 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0038_orderitem_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at_sale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='prev_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='SalesStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cell', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(default='active', max_length=10)),
                ('legacy_id', models.PositiveIntegerField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_sales_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_staff',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='sales.salesstaff'),
        ),
    ]
