# Generated by Django 4.2.30 on 2026-10-07 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0026_product_batch'),
        ('customer', '0006_customer_tenant'),
        ('sales', '0039_sales_staff_and_invoice_balances'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeSaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('kind', models.CharField(choices=[('complete', 'Complete Bill'), ('random', 'Random'), ('legacy', 'Legacy')], default='random', max_length=10)),
                ('customer_name', models.CharField(blank=True, default='', max_length=150)),
                ('return_date', models.DateField()),
                ('gross', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('less_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_returned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prev_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trade_returns', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_returns', to='customer.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_returns', to='sales.order')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_returns', to='sales.salesstaff')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_trade_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trade_sale_returns',
                'ordering': ['-return_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeSaleReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('bonus_quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('retail', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('disc_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productbatch')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_return_items', to='sales.orderitem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.tradesalereturn')),
            ],
            options={
                'db_table': 'trade_sale_return_items',
            },
        ),
    ]
