# Generated by Django 4.2.30 on 2026-10-09 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_ledgeraccount_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0043_invoiceprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('vtype', models.CharField(default='receipt', max_length=20)),
                ('date', models.DateField()),
                ('chq_no', models.CharField(blank=True, default='', max_length=40)),
                ('chq_date', models.DateField(blank=True, null=True)),
                ('bank', models.CharField(blank=True, default='', max_length=80)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vouchers', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='sales.salesstaff')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trade_vouchers',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.PositiveIntegerField(default=1)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unallocated', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_lines', to='company.ledgeraccount')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.voucher')),
            ],
            options={
                'db_table': 'trade_voucher_lines',
                'ordering': ['voucher', 'line'],
            },
        ),
    ]
