# Generated by Django 4.2.30 on 2026-10-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0044_trade_vouchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='legacy',
            field=models.BooleanField(default=False),
        ),
    ]
