# Generated by Django 4.2.30 on 2026-10-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0045_voucher_legacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceprofile',
            name='acct_no',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
