# Generated by Django 4.2.30 on 2026-10-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0046_invoiceprofile_acct_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceprofile',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='invoiceprofile',
            name='bank_title',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='invoiceprofile',
            name='easypaisa_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
