# Generated by Django 4.2.30 on 2026-10-10 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_category_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0047_invoiceprofile_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('kind', models.CharField(choices=[('add', 'Damage Stock (Add)'), ('less', 'Damage Stock (Less)')], max_length=4)),
                ('date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_damage_stocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trade_damage_stock',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='salesstaff',
            name='cnic',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='salesstaff',
            name='manager_cell1',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='salesstaff',
            name='manager_cell2',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.CreateModel(
            name='DamageStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.PositiveIntegerField(default=1)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('qty', models.IntegerField(default=0)),
                ('pur_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sale_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('retail_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_items', to='products.productbatch')),
                ('damage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.damagestock')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damage_items', to='products.product')),
            ],
            options={
                'db_table': 'trade_damage_stock_items',
                'ordering': ['line'],
            },
        ),
        migrations.AddField(
            model_name='damagestock',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_stocks', to='sales.salesstaff'),
        ),
        migrations.AddField(
            model_name='damagestock',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_damage_stocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='damagestock',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_stocks', to='sales.voucher'),
        ),
    ]
