# Generated by Django 4.2.30 on 2026-10-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0048_damagestock_salesstaff_cnic_salesstaff_manager_cell1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='fare_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='goods_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SHIPPED', 'In Transit'), ('DELIVERED', 'Delivered'), ('RECEIVED', 'Received'), ('RETURNED', 'Purchase Return'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
