# Generated by Django 4.2.30 on 2026-10-10 15:27

from django.conf import settings
from django.db import migrations, models
import datetime


LEGACY_YEARS = [  # legacy FinancialYear (FYID, FYName, FromDate, ToDate, YStatus)
    (3, '2023-24', datetime.date(2023, 1, 1), datetime.date(2024, 12, 31), 'inactive'),
    (4, '2025', datetime.date(2025, 1, 1), datetime.date(2025, 12, 31), 'inactive'),
    (5, '2026', datetime.date(2026, 1, 1), datetime.date(2026, 12, 31), 'active'),
]


def seed_years(apps, schema_editor):
    User = apps.get_model('users', 'User')
    FY = apps.get_model('sales', 'FinancialYear')
    owner = User.objects.filter(is_superuser=True).order_by('id').first()
    if not owner or FY.objects.exists():
        return
    for sno, title, f, t, st in LEGACY_YEARS:
        FY.objects.create(sno=sno, title=title, from_date=f, to_date=t, status=st, tenant_id=owner.pk)
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0049_purchase_fare_goods_returned'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=40)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('status', models.CharField(default='active', max_length=10)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_financial_years', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trade_financial_years',
                'ordering': ['sno'],
            },
        ),
        migrations.RunPython(seed_years, migrations.RunPython.noop),
    ]
