# Generated by Django 4.2.30 on 2026-10-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0050_financial_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagestock',
            name='bill_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='damagestock',
            name='legacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='bank',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='chq_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='chq_no',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='damagestock',
            name='kind',
            field=models.CharField(choices=[('add', 'Damage Stock (Add)'), ('less', 'Damage Stock (Less)'), ('oadd', 'Opening Stock (Add)'), ('oles', 'Opening Stock (Less)')], max_length=4),
        ),
    ]
