# Generated by Django 4.2.30 on 2026-10-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0051_opening_stock_and_vouchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagestock',
            name='kind',
            field=models.CharField(choices=[('add', 'Damage Stock (Add)'), ('less', 'Damage Stock (Less)'), ('oadd', 'Opening Stock (Add)'), ('oles', 'Opening Stock (Less)'), ('sexc', 'Stock Access (Excess)'), ('ssho', 'Stock Short')], max_length=4),
        ),
    ]
