# Generated by Django 4.2.29 on 2026-04-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='plain_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
