# Generated by Django 4.2.29 on 2026-06-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('customer', '0003_customer_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='company.area'),
        ),
    ]
