# Generated by Django 4.2.28 on 2026-03-05 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companycategory_company_category'),
        ('products', '0002_add_retail_price_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='company.companycategory', verbose_name='Origin Category'),
        ),
    ]
