# Generated by Django 4.2.30 on 2026-04-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_alter_wishlist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='batch',
            field=models.CharField(blank=True, help_text="Dynamic tag like 'SPECIALTY' or 'POPULAR'", max_length=100, null=True),
        ),
    ]
