# Generated by Django 4.2.30 on 2026-04-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_supplier_only',
            field=models.BooleanField(default=False, help_text='True if this is a B2B supplier product not yet active for retail'),
        ),
    ]
