# Generated by Django 4.2.28 on 2026-03-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pack_size',
            field=models.IntegerField(default=1, help_text='Number of items per pack'),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging',
            field=models.CharField(default='Piece', help_text='e.g. Unit, Pack, Box, Carton', max_length=100),
        ),
    ]
