# Generated by Django 4.2.29 on 2026-04-16 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0006_supplier_plain_password'),
        ('products', '0005_maincategory_alter_product_badge_alter_product_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproduct',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='supplier.supplier'),
        ),
    ]
