# Generated by Django 4.2.30 on 2026-04-16 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_purchaseorder_purchaseorderitem'),
        ('inventory', '0003_alter_stock_options_alter_warehouse_options_and_more'),
        ('products', '0005_product_is_supplier_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='supplier.supplier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.stock'),
        ),
    ]
