# Generated by Django 4.2.30 on 2026-04-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_purchaseorder_purchaseorderitem'),
        ('products', '0006_category_supplier_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug', 'supplier'), ('name', 'supplier')},
        ),
    ]
