# Generated by Django 4.2.28 on 2026-03-11 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
