# Generated by Django 4.2.28 on 2026-03-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pack_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='packaging',
        ),
    ]
