# Generated by Django 4.2.28 on 2026-03-16 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_sku'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='ProductAdditionalImage',
        ),
    ]
