# Generated by Django 4.2.29 on 2026-04-24 14:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_type', models.CharField(choices=[('HERO', 'Hero Banner'), ('PRODUCTS', 'Featured Products'), ('CATEGORIES', 'Categories'), ('NEWSLETTER', 'Newsletter'), ('TESTIMONIALS', 'Testimonials'), ('ABOUT', 'About Us'), ('WHY_CHOOSE', 'Why Choose Us'), ('PROMO', 'Promotional'), ('FAQ', 'FAQ Section'), ('CONTACT', 'Contact Section'), ('FOOTER', 'Footer Blocks'), ('CUSTOM', 'Custom Section')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('content', models.JSONField(default=dict, help_text='Store JSON data for buttons, links, etc.')),
                ('position', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('bg_color', models.CharField(default='#FFFFFF', max_length=50)),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='landing/bg/')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Landing Page Section',
                'verbose_name_plural': 'Landing Page Sections',
                'db_table': 'landing_page_sections',
                'ordering': ['position'],
            },
        ),
    ]
