# Generated by Django 4.2.29 on 2026-04-25 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_landingpagesection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandingPageSection',
        ),
    ]
