# Generated by Django 4.2.28 on 2026-03-16 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_productimage_productadditionalimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductAdditionalImage',
        ),
    ]
