# Generated by Django 4.2.28 on 2026-03-16 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_is_active'),
        ('products', '0015_productgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='company.company', verbose_name='Manufacturing Company'),
        ),
    ]
