# Generated by Django 4.2.29 on 2026-05-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_size_product_weight_supplierproduct_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reserved_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
