# Generated by Django 4.2.28 on 2026-03-24 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_is_active'),
        ('products', '0016_product_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='company_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='company.companycategory', verbose_name='Origin / Vendor Category'),
        ),
    ]
