# Generated by Django 4.2.29 on 2026-06-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_category_navbar_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_count',
            field=models.IntegerField(default=10),
        ),
    ]
