# Generated by Django 4.2.28 on 2026-03-24 10:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_company_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.FileField(blank=True, upload_to='main_categories/')),
                ('products', models.ManyToManyField(blank=True, related_name='main_categories', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Main Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='products_ma_slug_e8505d_idx'), models.Index(fields=['status'], name='products_ma_status_311749_idx')],
            },
        ),
    ]
