# Generated by Django 4.2.28 on 2026-06-26 09:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_min_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(blank=True, default='', max_length=50)),
                ('weight', models.CharField(blank=True, default='', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('quantity', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='store_products/')),
                ('description', models.TextField(blank=True, default='')),
                ('is_visible', models.BooleanField(default=True)),
                ('source', models.CharField(default='manual', max_length=20)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_products', to='products.category')),
            ],
            options={
                'verbose_name': 'Store Product',
                'verbose_name_plural': 'Store Products',
                'db_table': 'store_products',
                'ordering': ['-created_at'],
            },
        ),
    ]
