# Generated by Django 4.2.28 on 2026-03-26 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_supplier_user'),
        ('products', '0019_category_main_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='company.supplier', verbose_name='Supplier'),
        ),
    ]
