# Generated by Django 4.2.28 on 2026-06-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_stock_created_by'),
        ('products', '0019_storeproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('warehouse', 'sku'), ('warehouse', 'barcode')},
        ),
    ]
