# Generated by Django 4.2.29 on 2026-06-27 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0011_stock_tenant_stockmovement_tenant_warehouse_tenant'),
        ('products', '0020_alter_product_barcode_alter_product_sku_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_main_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('tenant', 'name'), ('tenant', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='maincategory',
            unique_together={('tenant', 'name'), ('tenant', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('tenant', 'warehouse', 'barcode'), ('tenant', 'warehouse', 'sku')},
        ),
    ]
