# Generated by Django 4.2.28 on 2026-04-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
    ]
