# Generated by Django 4.2.29 on 2026-04-06 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_supplier'),
        ('products', '0022_remove_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='company.supplier', verbose_name='Strategic Supplier'),
        ),
    ]
