# Generated by Django 4.2.29 on 2026-07-22 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company'),
        ('products', '0022_product_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='company.company'),
        ),
    ]
