# Generated by Django 4.2.29 on 2026-04-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_add_is_supplier_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived'), ('pending_procurement', 'Pending Procurement')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived'), ('pending_procurement', 'Pending Procurement')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived'), ('pending_procurement', 'Pending Procurement')], default='pending_procurement', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('sku', 'is_supplier_only'), ('barcode', 'is_supplier_only')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_supplier_only'], name='products_pr_is_supp_fef1fb_idx'),
        ),
    ]
