# Generated by Django 4.2.30 on 2026-10-09 15:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_clear_placeholder_barcodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateExpiryUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('staff', models.CharField(blank=True, default='', max_length=120)),
                ('old_expiry', models.DateField(blank=True, null=True)),
                ('new_expiry', models.DateField(blank=True, null=True)),
                ('old_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('new_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('old_sale', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('new_sale', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('old_retail', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('new_retail', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_updates', to='products.productbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_updates', to='products.product')),
            ],
            options={
                'db_table': 'product_rate_expiry_updates',
            },
        ),
    ]
