# Generated by Django 4.2.30 on 2026-10-10 05:48

from django.db import migrations, models


def number_categories(apps, schema_editor):
    """Give existing categories their Product Type Code (1, 2, 3 … per tenant,
    in the order they were created — the legacy CategID order)."""
    Category = apps.get_model('products', 'Category')
    seen = {}
    for c in Category.objects.order_by('tenant_id', 'created_at', 'name'):
        seen[c.tenant_id] = seen.get(c.tenant_id, 0) + 1
        Category.objects.filter(pk=c.pk).update(code=seen[c.tenant_id])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_rate_expiry_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(number_categories, migrations.RunPython.noop),
    ]
