# Generated by Django 4.2.28 on 2026-03-01 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='category',
            field=models.CharField(choices=[('users', 'User Management'), ('products', 'Product Management'), ('orders', 'Order Management'), ('inventory', 'Inventory Management'), ('settings', 'Settings'), ('roles', 'Roles & Permissions')], default='users', max_length=50),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_new_order', models.BooleanField(default=True)),
                ('notif_low_stock', models.BooleanField(default=True)),
                ('notif_new_user', models.BooleanField(default=False)),
                ('notif_weekly_report', models.BooleanField(default=True)),
                ('notif_marketing', models.BooleanField(default=False)),
                ('notif_sms', models.BooleanField(default=False)),
                ('theme', models.CharField(default='light', max_length=10)),
                ('accent_color', models.CharField(default='#007185', max_length=20)),
                ('compact_mode', models.BooleanField(default=False)),
                ('animations', models.BooleanField(default=True)),
                ('sidebar_collapsed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
