# Generated by Django 4.2.29 on 2026-04-20 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notification_customer_id_notification_supplier_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
