# Generated by Django 4.2.29 on 2026-04-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_useractivitylog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plain_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('role_assign', 'Role Assignment'), ('status_change', 'Status Change'), ('export', 'Export'), ('other', 'Other')], max_length=20),
        ),
    ]
