# Generated by Django 4.2.29 on 2026-05-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
