# Generated by Django 4.2.29 on 2026-06-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('users', '0007_user_page_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='areas',
            field=models.ManyToManyField(blank=True, related_name='managers', to='company.area'),
        ),
    ]
