# Generated by Django 4.2.29 on 2026-06-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='page_edit_permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
