# Generated by Django 4.2.28 on 2026-06-24 10:28
#
# The original auto-generated ``AddField(ManyToManyField)`` failed on production
# MariaDB with error 3780 ("Referencing column 'warehouse_id' and referenced column
# 'id' ... are incompatible"). Cause: the freshly-created through table inherited the
# server's *default* collation, which differs from the collation of the long-existing
# ``warehouses`` / ``users_user`` tables. MySQL/MariaDB require a FK column to share the
# referenced column's exact type AND collation.
#
# Fix: build the through table by hand, copying the precise COLUMN_TYPE (which captures
# length / unsigned) and COLLATION from each target PK at migrate-time, so it is always
# compatible regardless of the server's default collation. The model state still sees a
# normal ManyToManyField, so the ORM and future autodetection are unaffected.
#
# NOTE: SeparateDatabaseAndState runs the RunPython against the *pre*-state, which does
# not yet contain the M2M field, so we must derive the standard Django M2M table/column
# names directly rather than via User._meta.get_field('warehouses').

from django.db import migrations, models


def _id_column(cursor, table):
    cursor.execute(
        "SELECT COLUMN_TYPE, CHARACTER_SET_NAME, COLLATION_NAME "
        "FROM information_schema.COLUMNS "
        "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND COLUMN_NAME = 'id'",
        [table],
    )
    row = cursor.fetchone()
    if not row:
        raise RuntimeError("Cannot introspect `%s`.`id` to build the M2M table" % table)
    return row  # (column_type, charset, collation)


def _coldef(col_name, info):
    col_type, charset, collation = info
    parts = ["`%s` %s" % (col_name, col_type)]
    if charset:
        parts.append("CHARACTER SET %s" % charset)
    if collation:
        parts.append("COLLATE %s" % collation)
    parts.append("NOT NULL")
    return " ".join(parts)


def _names(apps):
    """Standard Django M2M table/column names for User.warehouses -> inventory.Warehouse."""
    user_table = apps.get_model('users', 'User')._meta.db_table          # users_user
    wh_table = apps.get_model('inventory', 'Warehouse')._meta.db_table   # warehouses
    return user_table, wh_table, user_table + '_warehouses', 'user_id', 'warehouse_id'


def create_through(apps, schema_editor):
    conn = schema_editor.connection
    user_table, wh_table, through, user_col, wh_col = _names(apps)

    c = conn.cursor()
    # Clear any half-built table left by the original failed migration (MySQL DDL
    # auto-commits, so the CREATE TABLE can survive even though the FK add failed).
    c.execute("DROP TABLE IF EXISTS `%s`" % through)

    if conn.vendor != 'mysql':
        # Dev/test backends (e.g. sqlite) - dynamic typing, a plain table suffices.
        c.execute(
            "CREATE TABLE \"%s\" (id integer NOT NULL PRIMARY KEY AUTOINCREMENT, "
            "\"%s\" varchar(64) NOT NULL, \"%s\" varchar(64) NOT NULL, "
            "UNIQUE (\"%s\", \"%s\"))" % (through, user_col, wh_col, user_col, wh_col)
        )
        return

    user_def = _coldef(user_col, _id_column(c, user_table))
    wh_def = _coldef(wh_col, _id_column(c, wh_table))
    c.execute(
        "CREATE TABLE `%(through)s` ("
        " `id` bigint NOT NULL AUTO_INCREMENT,"
        " %(user_def)s,"
        " %(wh_def)s,"
        " PRIMARY KEY (`id`),"
        " UNIQUE KEY `%(through)s_uniq` (`%(user_col)s`, `%(wh_col)s`),"
        " KEY `%(through)s_wh_idx` (`%(wh_col)s`),"
        " CONSTRAINT `%(through)s_user_fk`"
        "  FOREIGN KEY (`%(user_col)s`) REFERENCES `%(user_table)s` (`id`),"
        " CONSTRAINT `%(through)s_wh_fk`"
        "  FOREIGN KEY (`%(wh_col)s`) REFERENCES `%(wh_table)s` (`id`)"
        ")" % {
            'through': through, 'user_def': user_def, 'wh_def': wh_def,
            'user_col': user_col, 'wh_col': wh_col,
            'user_table': user_table, 'wh_table': wh_table,
        }
    )


def drop_through(apps, schema_editor):
    _ut, _wt, through, _uc, _wc = _names(apps)
    schema_editor.connection.cursor().execute("DROP TABLE IF EXISTS `%s`" % through)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_warehouse_area_warehouse_is_active'),
        ('users', '0009_user_page_edit_permissions'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='user',
                    name='warehouses',
                    field=models.ManyToManyField(blank=True, related_name='admins', to='inventory.warehouse'),
                ),
            ],
            database_operations=[
                migrations.RunPython(create_through, drop_through),
            ],
        ),
    ]
