# Generated by Django 4.2.28 on 2026-06-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_warehouse_area_warehouse_is_active'),
        ('users', '0009_user_page_edit_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='warehouses',
            field=models.ManyToManyField(blank=True, related_name='admins', to='inventory.warehouse'),
        ),
    ]
