# Generated by Django 4.2.29 on 2026-05-08 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cms/media/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=20)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(choices=[('header', 'Header Main Menu'), ('footer_1', 'Footer Quick Links'), ('footer_2', 'Footer Customer Care')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Al-Qavi Hub', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='cms/branding/')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='cms/branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='cms/branding/')),
                ('primary_color', models.CharField(default='#c45500', max_length=20)),
                ('secondary_color', models.CharField(default='#111c31', max_length=20)),
                ('show_announcement', models.BooleanField(default=True)),
                ('announcement_text', models.CharField(default='Free Delivery on all orders over Rs. 5000!', max_length=255)),
                ('announcement_link', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp_number', models.CharField(default='+923000000000', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(default='info@alqavihub.com', max_length=254)),
                ('address', models.TextField(blank=True, null=True)),
                ('google_maps_url', models.TextField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('tiktok_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('meta_title', models.CharField(default='Al-Qavi Hub | Luxury Cosmetics', max_length=255)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='cms/seo/')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pixel_id', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Site Settings',
            },
        ),
        migrations.CreateModel(
            name='WebsiteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for admin identification', max_length=255)),
                ('section_type', models.CharField(choices=[('hero', 'Hero Slider / Banner'), ('products', 'Product Grid'), ('categories', 'Category Showcase'), ('about', 'About Us / Text Block'), ('testimonials', 'Customer Reviews'), ('faq', 'FAQ Accordion'), ('newsletter', 'Newsletter Signup'), ('gallery', 'Media Gallery'), ('video', 'Video Section'), ('promotion', 'Promotional Banner')], max_length=50)),
                ('content', models.JSONField(default=dict, help_text='Stores all settings, text, and media IDs for this section')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.navigationmenu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.navigationitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
