# Generated by Django 4.2.29 on 2026-05-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(max_length=500, upload_to='cms/media/'),
        ),
    ]
