# Generated by Django 4.2.29 on 2026-05-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_mediaasset_file'),
    ]

    operations = [
    ]
