# Generated by Django 4.2.29 on 2026-05-09 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_add_pages_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text="URL friendly name (e.g. 'about-us')", unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='websitesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero Slider / Banner'), ('products', 'Product Grid'), ('categories', 'Category Showcase'), ('about', 'About Us / Text Block'), ('testimonials', 'Customer Reviews'), ('faq', 'FAQ Accordion'), ('newsletter', 'Newsletter Signup'), ('gallery', 'Media Gallery'), ('video', 'Video Section'), ('promotion', 'Promotional Banner'), ('marquee', 'Scrolling Text Marquee'), ('brands', 'Brand Logos'), ('floating_canvas', 'Interactive Floating Canvas')], max_length=50),
        ),
        migrations.AddField(
            model_name='websitesection',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cms.page'),
        ),
    ]
