# Generated by Django 4.2.29 on 2026-05-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_page_alter_websitesection_section_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitesection',
            name='page',
        ),
        migrations.AlterField(
            model_name='websitesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero Slider / Banner'), ('products', 'Product Grid'), ('categories', 'Category Showcase'), ('about', 'About Us / Text Block'), ('testimonials', 'Customer Reviews'), ('faq', 'FAQ Accordion'), ('newsletter', 'Newsletter Signup'), ('gallery', 'Media Gallery'), ('video', 'Video Section'), ('promotion', 'Promotional Banner'), ('brands', 'Brands Slider'), ('stats', 'Impact Statistics'), ('features', 'Core Features Grid'), ('steps', 'How It Works / Steps'), ('spotlight', 'Product Spotlight'), ('marquee', 'Announcement Ticker'), ('banner_split', 'Split Image/Text Banner'), ('contact', 'Contact Information'), ('map', 'Google Maps Embed'), ('parallax', 'Parallax Scrolling'), ('html', 'Custom HTML Widget')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
