# Generated by Django 4.2.29 on 2026-05-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_remove_websitesection_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_bg_color',
            field=models.CharField(default='#131921', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_duration',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_scroll',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_scroll_speed',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_text_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
    ]
