# Generated by Django 4.2.28 on 2026-06-18 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('inbound', 'Income'), ('outbound', 'Expense'), ('both', 'Both')], default='both', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Payment Categories',
                'db_table': 'payment_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_type', models.CharField(choices=[('inbound', 'Income'), ('outbound', 'Expense')], default='inbound', max_length=10)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('mobile_wallet', 'Digital Wallet'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, default='', max_length=100)),
                ('payer_payee', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('sale', 'Sale'), ('purchase', 'Purchase Payment'), ('sale_return', 'Sale Return'), ('purchase_return', 'Purchase Return')], default='manual', max_length=20)),
                ('source_type', models.CharField(blank=True, default='', max_length=30)),
                ('source_id', models.CharField(blank=True, default='', max_length=64)),
                ('is_auto', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.paymentcategory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['source', 'source_type', 'source_id'], name='payments_source_idx'),
        ),
    ]
