# Generated by Django 4.2.28 on 2026-03-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_delete_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
