# Generated by Django 4.2.29 on 2026-04-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymentcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcategory',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived'), ('pending_procurement', 'Pending Procurement')], default='active', max_length=20),
        ),
    ]
