# Generated by Django 4.2.28 on 2026-06-23 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0003_alter_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('order', 'Sale Order'), ('purchaseorder', 'Purchase Order'), ('salereturn', 'Sale Return'), ('purchasereturn', 'Purchase Return')], max_length=20)),
                ('source_id', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('online', 'Online'), ('wallet', 'Mobile Wallet'), ('other', 'Other')], default='cash', max_length=20)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('slip', models.FileField(blank=True, null=True, upload_to='installment_slips/')),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='confirmed', max_length=10)),
                ('direction', models.CharField(choices=[('inbound', 'Money In'), ('outbound', 'Money Out')], default='inbound', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transaction_payments',
                'ordering': ['paid_at', 'created_at'],
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='txn_pay_source_idx')],
            },
        ),
    ]
