# Generated by Django 4.2.28 on 2026-06-24 10:28
#
# The original auto-generated AddField(ForeignKey -> inventory.Warehouse) failed on
# production MariaDB with error 3780: the new `warehouse_id char(32)` column inherited
# the `payments` / `transaction_payments` table collation, which differs from that of
# `warehouses.id` (production has inconsistent per-table collations). We add the column
# with the EXACT type + collation of `warehouses.id` so the FK is compatible, and we
# tolerate a column the original failed run already created (MySQL DDL auto-commits, so
# the ADD COLUMN can survive even though the follow-up ADD CONSTRAINT failed).

from django.db import migrations, models
import django.db.models.deletion


TABLES = ('payments', 'transaction_payments')


def _wh_id_info(cursor, wh_table):
    cursor.execute(
        "SELECT COLUMN_TYPE, CHARACTER_SET_NAME, COLLATION_NAME "
        "FROM information_schema.COLUMNS "
        "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND COLUMN_NAME = 'id'",
        [wh_table],
    )
    row = cursor.fetchone()
    if not row:
        raise RuntimeError("Cannot introspect `%s`.`id`" % wh_table)
    return row


def _coldef(info):
    col_type, charset, collation = info
    parts = ["`warehouse_id` %s" % col_type]
    if charset:
        parts.append("CHARACTER SET %s" % charset)
    if collation:
        parts.append("COLLATE %s" % collation)
    parts.append("NULL")
    return " ".join(parts)


def _col_exists(cursor, table, col):
    cursor.execute(
        "SELECT 1 FROM information_schema.COLUMNS "
        "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND COLUMN_NAME = %s",
        [table, col],
    )
    return cursor.fetchone() is not None


def _fk_exists(cursor, table, name):
    cursor.execute(
        "SELECT 1 FROM information_schema.TABLE_CONSTRAINTS "
        "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND CONSTRAINT_NAME = %s "
        "AND CONSTRAINT_TYPE = 'FOREIGN KEY'",
        [table, name],
    )
    return cursor.fetchone() is not None


def _fk_name(table):
    return "%s_warehouse_id_fk_warehouses" % table


def forwards(apps, schema_editor):
    conn = schema_editor.connection
    wh_table = apps.get_model('inventory', 'Warehouse')._meta.db_table
    c = conn.cursor()

    if conn.vendor != 'mysql':
        for table in TABLES:
            if not _col_exists(c, table, 'warehouse_id'):
                c.execute('ALTER TABLE "%s" ADD COLUMN warehouse_id char(32) NULL' % table)
        return

    coldef = _coldef(_wh_id_info(c, wh_table))
    for table in TABLES:
        if _col_exists(c, table, 'warehouse_id'):
            # The failed original run may have added it with the wrong collation - fix it.
            c.execute("ALTER TABLE `%s` MODIFY %s" % (table, coldef))
        else:
            c.execute("ALTER TABLE `%s` ADD COLUMN %s" % (table, coldef))
        fk = _fk_name(table)
        if not _fk_exists(c, table, fk):
            c.execute(
                "ALTER TABLE `%s` ADD CONSTRAINT `%s` FOREIGN KEY (`warehouse_id`) "
                "REFERENCES `%s` (`id`) ON DELETE SET NULL" % (table, fk, wh_table)
            )


def backwards(apps, schema_editor):
    conn = schema_editor.connection
    c = conn.cursor()
    for table in TABLES:
        fk = _fk_name(table)
        if conn.vendor == 'mysql' and _fk_exists(c, table, fk):
            c.execute("ALTER TABLE `%s` DROP FOREIGN KEY `%s`" % (table, fk))
        if _col_exists(c, table, 'warehouse_id'):
            c.execute("ALTER TABLE `%s` DROP COLUMN `warehouse_id`" % table)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_warehouse_area_warehouse_is_active'),
        ('payments', '0004_transactionpayment'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='payment',
                    name='warehouse',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='inventory.warehouse'),
                ),
                migrations.AddField(
                    model_name='transactionpayment',
                    name='warehouse',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_payments', to='inventory.warehouse'),
                ),
            ],
            database_operations=[
                migrations.RunPython(forwards, backwards),
            ],
        ),
    ]
