# Generated by Django 4.2.28 on 2026-06-24 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_warehouse_area_warehouse_is_active'),
        ('payments', '0004_transactionpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='transactionpayment',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_payments', to='inventory.warehouse'),
        ),
    ]
