# Generated by Django 4.2.29 on 2026-07-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_tenant_transactionpayment_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('sale', 'Sale'), ('purchase', 'Purchase Payment'), ('sale_return', 'Sale Return'), ('purchase_return', 'Purchase Return'), ('delivery', 'Delivery Charge')], default='manual', max_length=20),
        ),
    ]
