# Generated by Django 4.2.28 on 2026-04-13 16:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=255)),
                ('purchase_type', models.CharField(choices=[('carton', 'Carton'), ('single', 'Single')], max_length=20)),
                ('cartons', models.IntegerField(blank=True, null=True)),
                ('items_per_carton', models.IntegerField(blank=True, null=True)),
                ('total_quantity', models.IntegerField()),
                ('price_per_carton', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'stocks',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'db_table': 'warehouses',
            },
        ),
    ]
