# Generated by Django 4.2.29 on 2026-04-18 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_maincategory_options_maincategory_is_visible_and_more'),
        ('inventory', '0002_stock_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='products.supplierproduct'),
        ),
    ]
