# Generated by Django 4.2.28 on 2026-03-12 16:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_category_parent'),
        ('inventory', '0002_inventory_inventorymovement_stockadjustment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(max_length=100)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired')], default='Active', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Batches',
            },
        ),
        migrations.CreateModel(
            name='LowStockAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, max_digits=12)),
                ('alert_status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='productbatch',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productbatch',
            name='product',
        ),
        migrations.RenameField(
            model_name='inventorymovement',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='stockadjustment',
            old_name='user',
            new_name='adjusted_by',
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='inventory',
        ),
        migrations.AddField(
            model_name='inventory',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventory',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='last_stock_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity_available',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity_damaged',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity_in_transit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity_reserved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventory',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventory',
            name='reorder_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventory',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='new_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='previous_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('Main', 'Main'), ('Regional', 'Regional'), ('Store', 'Store')], default='Main', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Sale', 'Sale'), ('Transfer In', 'Transfer In'), ('Transfer Out', 'Transfer Out'), ('Adjustment', 'Adjustment'), ('Return', 'Return')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('Add', 'Add'), ('Remove', 'Remove')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason',
            field=models.CharField(choices=[('Damaged', 'Damaged'), ('Lost', 'Lost'), ('Correction', 'Correction')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'warehouse', 'batch_number')},
        ),
        migrations.DeleteModel(
            name='StockTransfer',
        ),
        migrations.AddField(
            model_name='lowstockalert',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='batch',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='current_stock',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='reserved_stock',
        ),
        migrations.DeleteModel(
            name='ProductBatch',
        ),
    ]
