# Generated by Django 4.2.28 on 2026-03-24 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_batch_lowstockalert_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='sku',
        ),
    ]
