# Generated by Django 4.2.29 on 2026-04-24 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_remove_supplier_contact_supplier_avatar_and_more'),
        ('inventory', '0003_stock_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='supplier.supplier'),
        ),
    ]
