# Generated by Django 4.2.29 on 2026-04-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_inventory_barcode_remove_inventory_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived'), ('pending_procurement', 'Pending Procurement')], default='active', max_length=20),
        ),
    ]
