# Generated by Django 4.2.29 on 2026-04-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stock_size_stock_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='movement_type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Transfer', 'Transfer'), ('Adjustment', 'Adjustment')], default='Purchase', max_length=20),
        ),
    ]
