# Generated by Django 4.2.28 on 2026-06-24 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0009_warehouse_area_warehouse_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stocks', to=settings.AUTH_USER_MODEL),
        ),
    ]
