# Generated by Django 4.2.29 on 2026-06-27 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0002_deliveryperson_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_delivery_persons', to=settings.AUTH_USER_MODEL),
        ),
    ]
