# Generated by Django 4.2.29 on 2026-07-01 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_stock_tenant_stockmovement_tenant_warehouse_tenant'),
        ('delivery', '0003_deliveryperson_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_persons', to='inventory.warehouse'),
        ),
    ]
