# Generated by Django 4.2.29 on 2026-07-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliveryperson_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
