# Generated by Django 4.2.30 on 2026-04-12 19:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the supplier', max_length=255)),
                ('company', models.CharField(help_text='Name of the company', max_length=255)),
                ('contact', models.CharField(help_text='Contact information (phone/email)', max_length=255)),
                ('address', models.TextField(help_text='Physical address of the supplier')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'suppliers',
            },
        ),
    ]
