# Generated by Django 4.2.29 on 2026-04-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_supplier_address_alter_supplier_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, help_text='Supplier email address', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=255, null=True),
        ),
    ]
