# Generated by Django 4.2.29 on 2026-07-17 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier', '0007_remove_supplier_contact_supplier_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_suppliers', to=settings.AUTH_USER_MODEL),
        ),
    ]
