# Generated by Django 4.2.28 on 2026-02-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('tagline', models.CharField(blank=True, max_length=255, verbose_name='Tagline / Slogan')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone Number')),
                ('whatsapp', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp Number')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('country', models.CharField(blank=True, default='Pakistan', max_length=100, verbose_name='Country')),
                ('website', models.URLField(blank=True, verbose_name='Website URL')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, verbose_name='About / Description')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter / X URL')),
                ('currency', models.CharField(default='PKR', max_length=10, verbose_name='Currency')),
                ('tax_number', models.CharField(blank=True, max_length=100, verbose_name='Tax / NTN Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
            },
        ),
    ]
