# Generated by Django 4.2.28 on 2026-03-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companycategory_company_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycategory',
            name='color',
            field=models.CharField(default='emerald', max_length=20),
        ),
        migrations.AddField(
            model_name='companycategory',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companycategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companycategory',
            name='type',
            field=models.CharField(choices=[('local', 'Local'), ('imported', 'Imported')], default='local', max_length=20),
        ),
    ]
