# Generated by Django 4.2.30 on 2026-10-06 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0006_customer_tenant'),
        ('supplier', '0009_backfill_supplier_tenant'),
        ('company', '0003_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('level', models.PositiveSmallIntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='company.accountgroup')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_account_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_groups',
                'ordering': ['code'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_id', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=255)),
                ('cell_no', models.CharField(blank=True, default='', max_length=40)),
                ('contact_person', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_accounts', to='company.area')),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_account', to='customer.customer')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='company.accountgroup')),
                ('supplier', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_account', to='supplier.supplier')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_ledger_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ledger_accounts',
                'ordering': ['acc_id'],
                'unique_together': {('tenant', 'acc_id')},
            },
        ),
    ]
