# Generated by Django 4.2.28 on 2026-03-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_companycategory_color_companycategory_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Supplier Name')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Contact Person')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone Number')),
                ('whatsapp', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp Number')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('country', models.CharField(default='Pakistan', max_length=100, verbose_name='Country')),
                ('tax_number', models.CharField(blank=True, max_length=100, verbose_name='Tax / NTN Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
    ]
