# Generated by Django 4.2.28 on 2026-03-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycategory',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
