# Generated by Django 4.2.28 on 2026-04-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_product_supplier'),
        ('company', '0007_supplier_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
