# Generated by Django 4.2.29 on 2026-04-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_supplierproduct'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supplierproduct',
            new_name='company_sup_supplie_6b10ec_idx',
            old_name='company_supp_li_7d9d2a_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierproduct',
            new_name='company_sup_product_d1bff1_idx',
            old_name='company_supp_prd_7d9d2a_idx',
        ),
    ]
